version: "3.8"

services:
  backend:
    build: 
      context: ./backend 
    ports:
      - "4000:4000"
    networks:
      - app_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development 
      - PORT=4000

  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"  
    networks:
      - app_network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app_network:
    driver: bridge